# List Comprehensions Lab

Complete the following set of exercises to solidify your knowledge of list comprehensions.

In [48]:
import os
import numpy as np
import pandas as pd

### 1. Use a list comprehension to create and print a list of consecutive integers starting with 1 and ending with 50.

In [2]:
[x for x in range(51)]

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50]

### 2. Use a list comprehension to create and print a list of even numbers starting with 2 and ending with 200.

In [8]:
[x for x in range(201) if x>2 and x%2==0]

[4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200]

### 3. Use a list comprehension to create and print a list containing all elements of the 10 x 4 Numpy array below.

In [10]:
a = np.array([[0.84062117, 0.48006452, 0.7876326 , 0.77109654],
       [0.44409793, 0.09014516, 0.81835917, 0.87645456],
       [0.7066597 , 0.09610873, 0.41247947, 0.57433389],
       [0.29960807, 0.42315023, 0.34452557, 0.4751035 ],
       [0.17003563, 0.46843998, 0.92796258, 0.69814654],
       [0.41290051, 0.19561071, 0.16284783, 0.97016248],
       [0.71725408, 0.87702738, 0.31244595, 0.76615487],
       [0.20754036, 0.57871812, 0.07214068, 0.40356048],
       [0.12149553, 0.53222417, 0.9976855 , 0.12536346],
       [0.80930099, 0.50962849, 0.94555126, 0.33364763]])

In [15]:
[i for x in a for i in x]

[0.84062117,
 0.48006452,
 0.7876326,
 0.77109654,
 0.44409793,
 0.09014516,
 0.81835917,
 0.87645456,
 0.7066597,
 0.09610873,
 0.41247947,
 0.57433389,
 0.29960807,
 0.42315023,
 0.34452557,
 0.4751035,
 0.17003563,
 0.46843998,
 0.92796258,
 0.69814654,
 0.41290051,
 0.19561071,
 0.16284783,
 0.97016248,
 0.71725408,
 0.87702738,
 0.31244595,
 0.76615487,
 0.20754036,
 0.57871812,
 0.07214068,
 0.40356048,
 0.12149553,
 0.53222417,
 0.9976855,
 0.12536346,
 0.80930099,
 0.50962849,
 0.94555126,
 0.33364763]

### 4. Add a condition to the list comprehension above so that only values greater than or equal to 0.5 are printed.

In [14]:
[k for x in a for k in x if (k >= 0.5)]

[0.84062117,
 0.7876326,
 0.77109654,
 0.81835917,
 0.87645456,
 0.7066597,
 0.57433389,
 0.92796258,
 0.69814654,
 0.97016248,
 0.71725408,
 0.87702738,
 0.76615487,
 0.57871812,
 0.53222417,
 0.9976855,
 0.80930099,
 0.50962849,
 0.94555126]

### 5. Use a list comprehension to create and print a list containing all elements of the 5 x 2 x 3 Numpy array below.

In [17]:
b = np.array([[[0.55867166, 0.06210792, 0.08147297],
        [0.82579068, 0.91512478, 0.06833034]],

       [[0.05440634, 0.65857693, 0.30296619],
        [0.06769833, 0.96031863, 0.51293743]],

       [[0.09143215, 0.71893382, 0.45850679],
        [0.58256464, 0.59005654, 0.56266457]],

       [[0.71600294, 0.87392666, 0.11434044],
        [0.8694668 , 0.65669313, 0.10708681]],

       [[0.07529684, 0.46470767, 0.47984544],
        [0.65368638, 0.14901286, 0.23760688]]])

In [22]:
[k for x in b for i in x for k in i]

[0.55867166,
 0.06210792,
 0.08147297,
 0.82579068,
 0.91512478,
 0.06833034,
 0.05440634,
 0.65857693,
 0.30296619,
 0.06769833,
 0.96031863,
 0.51293743,
 0.09143215,
 0.71893382,
 0.45850679,
 0.58256464,
 0.59005654,
 0.56266457,
 0.71600294,
 0.87392666,
 0.11434044,
 0.8694668,
 0.65669313,
 0.10708681,
 0.07529684,
 0.46470767,
 0.47984544,
 0.65368638,
 0.14901286,
 0.23760688]

### 5. Add a condition to the list comprehension above so that the last value in each subarray is printed, but only if it is less than or equal to 0.5.

In [25]:
[k for x in b for i in x for k in i if i[-1] <= 0.5]

[0.55867166,
 0.06210792,
 0.08147297,
 0.82579068,
 0.91512478,
 0.06833034,
 0.05440634,
 0.65857693,
 0.30296619,
 0.09143215,
 0.71893382,
 0.45850679,
 0.71600294,
 0.87392666,
 0.11434044,
 0.8694668,
 0.65669313,
 0.10708681,
 0.07529684,
 0.46470767,
 0.47984544,
 0.65368638,
 0.14901286,
 0.23760688]

### 6. Use a list comprehension to select and print the names of all CSV files in the */data* directory.

In [56]:
os.listdir("../data")

['sample_file_8.txt',
 'sample_file_9.txt',
 'sample_file_1.csv',
 'sample_file_0.csv',
 'sample_file_2.csv',
 'sample_file_3.csv',
 'sample_file_7.csv',
 'sample_file_6.csv',
 'sample_file_4.csv',
 'sample_file_5.csv',
 'sample_file_8.csv',
 'sample_file_9.csv',
 'sample_file_2.txt',
 'sample_file_3.txt',
 'sample_file_1.txt',
 'sample_file_0.txt',
 'sample_file_4.txt',
 'sample_file_5.txt',
 'sample_file_7.txt',
 'sample_file_6.txt']

In [58]:
[x for x in os.listdir("../data")]

['sample_file_8.txt',
 'sample_file_9.txt',
 'sample_file_1.csv',
 'sample_file_0.csv',
 'sample_file_2.csv',
 'sample_file_3.csv',
 'sample_file_7.csv',
 'sample_file_6.csv',
 'sample_file_4.csv',
 'sample_file_5.csv',
 'sample_file_8.csv',
 'sample_file_9.csv',
 'sample_file_2.txt',
 'sample_file_3.txt',
 'sample_file_1.txt',
 'sample_file_0.txt',
 'sample_file_4.txt',
 'sample_file_5.txt',
 'sample_file_7.txt',
 'sample_file_6.txt']

### 7. Use a list comprehension and the Pandas `read_csv` and `concat` methods to read all CSV files in the */data* directory and combine them into a single data frame. Display the top 10 rows of the resulting data frame.

In [ ]:
# df_all = pd.read_csv(os.path.join("../data", "sample_file_0.csv"))
df_all = pd.DataFrame(columns=[str(i) for i in list(range(20))])
# for x in os.listdir("../data"):
#     df = pd.read_csv(os.path.join("../data",x))
#     df_all = pd.concat([df_all, df])
#     pd.read_csv(os.path(x))
pd.concat([df_all, [pd.read_csv(os.path.join("../data",x)) for x in os.listdir("../data")]])
df_new = [pd.concat([df_all, pd.read_csv(os.path.join("../data",x))]) for x in os.listdir("../data")]

In [111]:
frames = [pd.read_csv(os.path.join("../data",x)) for x in os.listdir("../data")]
df_new = pd.concat(frames)

In [112]:
df_new

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.132453,0.106635,0.673568,0.507253,0.162925,0.130042,0.980388,0.623167,0.074066,0.111557,0.864664,0.093637,0.446974,0.022525,0.713369,0.707874,0.563506,0.982256,0.562498,0.968681
1,0.384938,0.767604,0.850528,0.605998,0.826172,0.667488,0.142045,0.086904,0.912348,0.892183,0.426389,0.776552,0.429496,0.602056,0.283769,0.166793,0.316878,0.688337,0.169525,0.966198
2,0.318691,0.675720,0.807189,0.752518,0.531342,0.703225,0.598293,0.921508,0.563333,0.184300,0.667625,0.270017,0.573440,0.163669,0.032852,0.689315,0.973684,0.719610,0.163670,0.724486
3,0.538593,0.291241,0.407187,0.613260,0.851424,0.962086,0.590512,0.980700,0.159022,0.684265,0.898633,0.470113,0.756593,0.282408,0.551369,0.732153,0.494100,0.792803,0.794426,0.837695
4,0.713271,0.156210,0.392800,0.702348,0.009400,0.030304,0.960066,0.688937,0.260252,0.634608,0.273775,0.264145,0.682941,0.908499,0.450950,0.200761,0.968324,0.221165,0.891382,0.398914
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,0.702566,0.092336,0.245083,0.918402,0.695110,0.886921,0.588605,0.950970,0.168079,0.783107,0.698836,0.120857,0.207432,0.824789,0.349212,0.818606,0.376941,0.886644,0.472826,0.551858
1,0.177005,0.649551,0.467321,0.449597,0.458872,0.815586,0.455132,0.729812,0.998528,0.048724,0.377391,0.729498,0.721515,0.566724,0.338366,0.877239,0.129824,0.773155,0.485385,0.686294
2,0.689556,0.445586,0.005691,0.150171,0.554146,0.492320,0.185612,0.060855,0.457443,0.847337,0.603072,0.346574,0.898464,0.482963,0.443979,0.430132,0.713078,0.302786,0.051382,0.203699
3,0.047188,0.854596,0.833368,0.043878,0.883505,0.786302,0.980916,0.004030,0.619601,0.547769,0.160962,0.545281,0.931623,0.991855,0.821099,0.654592,0.346710,0.183948,0.372739,0.739383
4,0.936065,0.725831,0.184239,0.677391,0.242726,0.125457,0.356254,0.937350,0.215774,0.212762,0.483018,0.573162,0.634487,0.423924,0.394633,0.766967,0.606719,0.538712,0.885516,0.667051

### 8. Use a list comprehension to select and print the column numbers for columns from the data set whose median is less than 0.48.

In [125]:
[column for column in df_new.columns if df_new[column].median()> 0.48]

# for column in df_new.columns:
#     if df_new[column].median()> 0.48:
#         print(column)

['0',
 '1',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '10',
 '11',
 '13',
 '15',
 '16',
 '18',
 '19']

### 9. Use a list comprehension to add a new column (20) to the data frame whose values are the values in column 19 minus 0.1. Display the top 10 rows of the resulting data frame.

In [131]:
df_new['20'] = [row-0.1 for row in df_new['19']]

In [132]:
df_new

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,0.132453,0.106635,0.673568,0.507253,0.162925,0.130042,0.980388,0.623167,0.074066,0.111557,...,0.093637,0.446974,0.022525,0.713369,0.707874,0.563506,0.982256,0.562498,0.968681,0.868681
1,0.384938,0.767604,0.850528,0.605998,0.826172,0.667488,0.142045,0.086904,0.912348,0.892183,...,0.776552,0.429496,0.602056,0.283769,0.166793,0.316878,0.688337,0.169525,0.966198,0.866198
2,0.318691,0.675720,0.807189,0.752518,0.531342,0.703225,0.598293,0.921508,0.563333,0.184300,...,0.270017,0.573440,0.163669,0.032852,0.689315,0.973684,0.719610,0.163670,0.724486,0.624486
3,0.538593,0.291241,0.407187,0.613260,0.851424,0.962086,0.590512,0.980700,0.159022,0.684265,...,0.470113,0.756593,0.282408,0.551369,0.732153,0.494100,0.792803,0.794426,0.837695,0.737695
4,0.713271,0.156210,0.392800,0.702348,0.009400,0.030304,0.960066,0.688937,0.260252,0.634608,...,0.264145,0.682941,0.908499,0.450950,0.200761,0.968324,0.221165,0.891382,0.398914,0.298914
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,0.702566,0.092336,0.245083,0.918402,0.695110,0.886921,0.588605,0.950970,0.168079,0.783107,...,0.120857,0.207432,0.824789,0.349212,0.818606,0.376941,0.886644,0.472826,0.551858,0.451858
1,0.177005,0.649551,0.467321,0.449597,0.458872,0.815586,0.455132,0.729812,0.998528,0.048724,...,0.729498,0.721515,0.566724,0.338366,0.877239,0.129824,0.773155,0.485385,0.686294,0.586294
2,0.689556,0.445586,0.005691,0.150171,0.554146,0.492320,0.185612,0.060855,0.457443,0.847337,...,0.346574,0.898464,0.482963,0.443979,0.430132,0.713078,0.302786,0.051382,0.203699,0.103699
3,0.047188,0.854596,0.833368,0.043878,0.883505,0.786302,0.980916,0.004030,0.619601,0.547769,...,0.545281,0.931623,0.991855,0.821099,0.654592,0.346710,0.183948,0.372739,0.739383,0.639383
4,0.936065,0.725831,0.184239,0.677391,0.242726,0.125457,0.356254,0.937350,0.215774,0.212762,...,0.573162,0.634487,0.423924,0.394633,0.766967,0.606719,0.538712,0.885516,0.667051,0.567051

### 10. Use a list comprehension to extract and print all values from the data set that are between 0.7 and 0.75.

In [142]:
df_list = [df_new[x].tolist() for x in df_new.columns]
[k for x in df_list for k in x if k > 0.7 and k < 0.75]

[0.7132714209987683,
 0.7280006345208285,
 0.7347510852128797,
 0.7025657075988269,
 0.7132714209987683,
 0.7280006345208285,
 0.7347510852128797,
 0.7025657075988269,
 0.736029494090402,
 0.7472962776291713,
 0.7258310816144985,
 0.736029494090402,
 0.7472962776291713,
 0.7258310816144985,
 0.7343092314001137,
 0.7358941798147411,
 0.7365416322783028,
 0.7088042362916818,
 0.7343092314001137,
 0.7088042362916818,
 0.7358941798147411,
 0.7365416322783028,
 0.7023481768180954,
 0.7329024831531535,
 0.7023481768180954,
 0.7329024831531535,
 0.7133695725698419,
 0.7476323136755818,
 0.7008930873050235,
 0.7133695725698419,
 0.7476323136755818,
 0.7008930873050235,
 0.7032248108904495,
 0.7150799992177622,
 0.7173964318670598,
 0.7357618655811269,
 0.7013619954419494,
 0.7268545088531969,
 0.7032248108904495,
 0.7150799992177622,
 0.7173964318670598,
 0.7013619954419494,
 0.7357618655811269,
 0.7268545088531969,
 0.7306642125209889,
 0.7124169515124726,
 0.71223975981198,
 0.7383982036983279,
 0.7306642125209889,
 0.7383982036983279,
 0.7124169515124726,
 0.71223975981198,
 0.7298115760258881,
 0.7298115760258881,
 0.7051334608870933,
 0.7321333453970806,
 0.7051334608870933,
 0.7321333453970806,
 0.7178166705957928,
 0.7374449181749492,
 0.7178166705957928,
 0.7374449181749492,
 0.7159290265157912,
 0.7159290265157912,
 0.7294980584878026,
 0.7294980584878026,
 0.7215147068185102,
 0.7215147068185102,
 0.7045750112959754,
 0.7111584953876777,
 0.7209375615129192,
 0.7045750112959754,
 0.7111584953876777,
 0.7209375615129192,
 0.7133690799930356,
 0.7396561066717461,
 0.7303553716733908,
 0.7133690799930356,
 0.7396561066717461,
 0.7303553716733908,
 0.7078738356977186,
 0.7321533684342264,
 0.7356923324968598,
 0.7390312927111312,
 0.7078738356977186,
 0.7321533684342264,
 0.7356923324968598,
 0.7390312927111312,
 0.7490680818183477,
 0.7085098152301276,
 0.7130781095091867,
 0.7490680818183477,
 0.7085098152301276,
 0.7130781095091867,
 0.7196096371031628,
 0.7264121114538001,
 0.7196096371031628,
 0.7264121114538001,
 0.7244863338885654,
 0.7393833032570581,
 0.7244863338885654,
 0.7393833032570581,
 0.7376946446827494,
 0.7033930409580709,
 0.7274869207330491,
 0.7376946446827494,
 0.7033930409580709,
 0.7274869207330491]